	.computer_type_col
	{
		width: {COMPUTERTYPECOLWIDTH}%;
	}

	.location_col
	{
		display: {LOCATIONCOLDISPLAY};
		width: 10%;
	}

	.highlight
	{
		background-color: #3CC;
	}

	.computer_list div.row:nth-child(2n+1)
	{
		background-color:{MAINODDROW};
	}

	.computer_list div.row:nth-child(2n)
	{
		background-color:{MAINEVENROW};
	}

	.locidAll
	{
		display: {DISPLAYALL};
	}
/* Locations Classes */
{LOCATIONSCLASSES}