	<table id="formTable" width="100%">
		<tr>
			<td>
				<div class="cell header" style="width:15%;">Name:</div>
				<div class="cell bottom_border" id="name" style="width:33%;margin:0 1% 0 1%;text-align:center;">{NAME}</div>
				<div class="cell header" style="width:15%;">Date:</div>
				<div class="cell bottom_border" id="date" style="width:33%;margin:0 1% 0 1%;text-align:center;">{DATE}</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="cell header" style="width:15%">Phone:</div></div>
				<div class="cell bottom_border" style="width:33%;margin:0 1% 0 1%;text-align:center;">{PHONE}</div>
				<div class="cell header" style="width:15%">Email address:</div>
				<div class="cell bottom_border" style="width:33%;margin:0 1% 0 1%;text-align:center;">{EMAIL}</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="cell header" style="width:15%">NUID#:</div>
				<div class="cell bottom_border" style="width:33%;margin:0 1% 0 1%;text-align:center;">{NUID}</div>
				<div class="cell header" style="width:15%">Status:</div>
				<div class="cell bottom_border" style="width:33%;margin:0 1% 0 1%;text-align:center;">{STATUS}</div?
			</td>
		</tr>
		<tr>
			<td class="top_space">
				<div class="cell header" style="width:15%">Computer:</div>
				<div class="cell bottom_border" style="width:83%;margin:0 1% 0 1%;">{BRAND} {TYPE}</div>
			</td>
		</tr>
		<tr>
			<td id="laptopR1">
				<div class="cell header" style="width:15%">Laptop power supply:</div>
				<div class="cell bottom_border" style="width:33%;margin:0 1% 0 1%;text-align:center;">{POWERSUPPLY}</div>
				<div class="cell header" style="width:15%">Laptop case:</div>
				<div class="cell bottom_border" style="width:33%;margin:0 1% 0 1%;text-align:center;">{LAPTOPCASE}</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="cell header" style="width:15%">External ethernet card:</div>
				<div class="cell bottom_border" style="width:33%;margin:0 1% 0 1%;text-align:center;">{ETHCARD}</div>
				<div class="cell header" style="width:15%">External wireless card:</div>
				<div class="cell bottom_border" style="width:33%;margin:0 1% 0 1%;text-align:center;">{WIRELESSCARD}</div>
			</td>
		</tr>
		<tr>
			<td class="top_space">
				<div class="cell header bottom_border" style="width:100%">
					CDs left with the computer
				</div>
			</td>
		</tr>
		<tr>
			<td>
				{CDS}
			</td>
		</tr>
		<tr>
			<td class="top_space">
				<div class="row_wide">
					<div class="cell header bottom_border" style="width:50%">Username:</div>
					<div class="cell header bottom_border" style="width:50%">Password:</div>
				</div>
{ACCOUNTS}			</td>
		</tr>
		<tr>
			<td class="top_space">
				<div class="cell header bottom_border" style="width:100%">
					Problems
				</div>
			</td>
		</tr>
		<tr>
			<td>
				{PROBLEMS}
			</td>
		</tr>
	</table>
	<div style="position: absolute;bottom: 15px;left: 15px;width:90%; display:none;">
		<div class="row_wide">
			<div class="cell" style="width:20%;font-size:small">
				Customer signature on pickup:
			</div>
			<div class="cell" style="width:1%">
			</div>
			<div class="cell bottom_border" style="width:79%">
				&nbsp;
			</div>
		</div>
		<div class="row_wide top_space">
			<div class="cell" style="width:30%; text-align:center;">
				Computer was:
			</div>
			<div class="cell" style="width:8%; text-align:center;">
				Fixed
			</div>
			<div class="cell" style="width:1%; text-align:center;">
				/
			</div>
			<div class="cell" style="width:8%; text-align:center;">
				Checked
			</div>
			<div class="cell" style="width:6%; text-align:center;">
			</div>
			<div class="cell" style="width:30%; text-align:center;">
				User Called:
			</div>
			<div class="cell" style="width:8%; text-align:center;">
				Yes
			</div>
			<div class="cell" style="width:1%; text-align:center;">
				/
			</div>
			<div class="cell" style="width:8%; text-align:center;">
				No
			</div>
		</div>
	</div>
	<div class="row_wide">
		<div class="top_space cell" style="position: absolute;bottom: 15px;left: 15px;text-align:center;width:100%">
			{TIDL}
		</div>
	</div>