	<form name="outForm" action="checkin.php" method="post">
		<input type="hidden" name="uid" value="{UID}">
		<input type="hidden" name="date" value="{DATE}">
		<input type="hidden" name="phone" value="">
		<input type="hidden" name="email" value="">
		<input type="hidden" name="username" value="">
		<input type="hidden" name="facstaffstu" value="">
		<input type="hidden" name="computer" value="">
		<input type="hidden" name="compType" value="">
		<input type="hidden" name="powersupply" value="">
		<input type="hidden" name="caseText" value="">
		<input type="hidden" name="ethernet" value="">
		<input type="hidden" name="wireless" value="">
		<input type="hidden" name="cds" value="">
		<input type="hidden" name="accounts" value="">		<!-- basics work.  need to add the ablity for no password -->
		<input type="hidden" name="prob" value="">
		<input type="hidden" name="compid" value="">
		<input type="hidden" name="checkout" value="no">
		<input type="hidden" name="backup" value="">
		<input type="hidden" name="street" value="">
		<input type="hidden" name="city" value="">
		<input type="hidden" name="state" value="">
		<input type="hidden" name="zip" value="">
	</form>
