	<div id="searchSection" style="display:none;">
		<form name="searchForm" action="javascript:ticketSearch('other','only','user','status','no')">
			<div class="row">
				<input type="text" value="" name="search" />
			</div>
			<div class="row top_space">
				<input type="submit" value="Search" /><input type="button" value="Cancel" onclick="cancelAction()" />
			</div>
		</form>
		<div id="searchOut"></div>
	</div>