<html>
	<head></head>
	<body>
		<p>{NAME}</p>
		<p>The status of your ticket at the UNL Computer Help Center has been changed to <span style="font-weight:bold;">{STATUS}</span>. Please go to <a href="https://mychc.unl.edu/ticket_detail.php?tid={TID}">https://mychc.unl.edu</a> or call 402-472-3970 for details.</p>
		<p>
			<div style="clear:both">
				Information Services Computer Help Center
			</div>
			<div style="clear:both">
				<div style="float:left; width:20em">
					Information Services
				</div>
				<div style="float:left; width:20em">
					E-Mail:
					<a href="mailto:ischc@unl.edu">
						ischc@unl.edu
					</a>
				</div>
			</div>
			<div style="clear:both">
				<div style="float:left; width:20em">
					University of Nebraska - Lincoln
				</div>
				<div style="float:left; width:20em">
					<a href="http://ischc.unl.edu">
						http://ischc.unl.edu
					</a>
				</div>
			</div>
			<div style="clear:both">
				<div style="float:left; width:20em">
					Lincoln, NE 68588-0203
				</div>
				<div style="float:left; width:20em">
					472-3970 toll free (866-472-3970)
				</div>
			</div>
		</p>
	</body>
</html>