					<div class="row_wide">
						<div class="cell" style="width:{CHECKBOXWIDTH}%;">
							<input type="checkbox" name="tid{TID}" value="{TID}" onclick="updateOutBox(this)"{CHECKBOXSTYLE}{DONECHECK}{REPAIRCENTER} />
						</div>
						<div class="cell" style="width:{CELLWIDTH}%; text-align:center;">
							{BRAND} {TYPE}
						</div>
						<div class="cell" style="width:{CELLWIDTH}%; text-align:center;">
							{SERIALNUMBER}
						</div>
						<div class="cell" style="width:{CELLWIDTH}%; text-align:center;">
							{LTID}
						</div>
						<div class="cell" style="width:{CELLWIDTH}%; text-align:center;"{CELLSTYLE}>
							{LOCATION}
						</div>
					</div>
