			<div class="row" id="{ROWID}" style="width: 98%; margin-top: 0px; margin-right: 1%; margin-bottom: 0px; margin-left: 1%; ">
				<div class="cell" style="width:100%;{BACKGROUND}">
					<div class="cell" style="width: 20%; ">
						<a href="ticket_detail.php?tid={TID}">{LTID}</a>
					</div>
					<div class="cell" style="width: 20%; ">{DATE}</div>
					<div class="cell" style="width: 20%; ">{BRAND}</div>
					<div class="cell" style="width: 20%; ">{TYPE}</div>
					<div class="cell" style="width: 20%; ">{STATUS}</div>
				</div>
			</div>
