				<div id="{TICKETNUM}" class="cell row" style="{ROWSTYLE}">
					<div class="cell" style="width:2%;">
						{ROWNUM}
					</div>
					<div class="cell" style="width:18%;">
						<a href="ticket_detail.php?tid={TID}">{TICKETNUM}</a>
					</div>
					<div class="cell" style="width:20%;">
						{NAME}
					</div>
					<div class="cell" style="width:10%;">
						{DATE}
					</div>
					<div class="cell" style="width:10%; text-align: center;">
						{REPAIRTYPE}
					</div>
					<div class="cell computer_type_col">
						{BRAND}
					</div>
					<div class="cell computer_type_col">
						{TYPE}
					</div>
					<div class="cell location_col">
						{LOCATION}
					</div>
				</div>
