<div class="row">
	<div class="cell" style="width:15%;">
		<div class="cell" style="clear:both;vertical-align:bottom;">{SUNDAY}</div>
		<div class="cell" style="width:80%;clear:both;vertical-align:bottom;">
			<span class="cell" style="width:100%; height:{SUNDAYPERCENT}px;background-color:#963;vertical-align:bottom;">
				<br>
			</span>
		</div>
	</div>
	<div class="cell" style="width:14%">
		<div class="cell" style="clear:both;vertical-align:bottom;">{MONDAY}</div>
		<div class="cell" style="width:80%;clear:both;vertical-align:bottom;">
			<span class="cell" style="width:100%; height:{MONDAYPERCENT}px;background-color:#963;vertical-align:bottom;">
				<br>
			</span>
		</div>
	</div>
	<div class="cell" style="width:14%">
		<div class="cell" style="clear:both;vertical-align:bottom;">{TUESDAY}</div>
		<div class="cell" style="width:80%;clear:both;vertical-align:bottom;">
			<span class="cell" style="width:100%; height:{TUESDAYPERCENT}px;background-color:#963;vertical-align:bottom;">
				<br>
			</span>
		</div>
	</div>
	<div class="cell" style="width:14%">
		<div class="cell" style="clear:both;vertical-align:bottom;">{WEDNESDAY}</div>
		<div class="cell" style="width:80%;clear:both;vertical-align:bottom;">
			<span class="cell" style="width:100%; height:{WEDNESDAYPERCENT}px;background-color:#963;vertical-align:bottom;">
				<br>
			</span>
		</div>
	</div>
	<div class="cell" style="width:14%">
		<div class="cell" style="clear:both;vertical-align:bottom;">{THURSDAY}</div>
		<div class="cell" style="width:80%;clear:both;vertical-align:bottom;">
			<span class="cell" style="width:100%; height:{THURSDAYPERCENT}px;background-color:#963;vertical-align:bottom;">
				<br>
			</span>
		</div>
	</div>
	<div class="cell" style="width:14%">
		<div class="cell" style="clear:both;vertical-align:bottom;">{FRIDAY}</div>
		<div class="cell" style="width:80%;clear:both;vertical-align:bottom;">
			<span class="cell" style="width:100%; height:{FRIDAYPERCENT}px;background-color:#963;vertical-align:bottom;">
				<br>
			</span>
		</div>
	</div>
	<div class="cell" style="width:15%">
		<div class="cell" style="clear:both;vertical-align:bottom;">{SATURDAY}</div>
		<div class="cell" style="width:80%;clear:both;vertical-align:bottom;">
			<span class="cell" style="width:100%; height:{SATURDAYPERCENT}px;background-color:#963;vertical-align:bottom;">
				<br>
			</span>
		</div>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:15%">
		Sunday
	</div>
	<div class="cell" style="width:14%">
		Monday
	</div>
	<div class="cell" style="width:14%">
		Tuesday
	</div>
	<div class="cell" style="width:14%">
		Wednesday
	</div>
	<div class="cell" style="width:14%">
		Thursday
	</div>
	<div class="cell" style="width:14%">
		Friday
	</div>
	<div class="cell" style="width:15%">
		Saturday
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		0
	</div>
	<div class="cell" style="width:5%">
		{HOUR0}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT0}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		1
	</div>
	<div class="cell" style="width:5%">
		{HOUR1}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT1}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		2
	</div>
	<div class="cell" style="width:5%">
		{HOUR2}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT2}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		3
	</div>
	<div class="cell" style="width:5%">
		{HOUR3}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT3}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		4
	</div>
	<div class="cell" style="width:5%">
		{HOUR4}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT4}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		5
	</div>
	<div class="cell" style="width:5%">
		{HOUR5}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT5}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		6
	</div>
	<div class="cell" style="width:5%">
		{HOUR6}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT6}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		7
	</div>
	<div class="cell" style="width:5%">
		{HOUR7}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT7}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		8
	</div>
	<div class="cell" style="width:5%">
		{HOUR8}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT8}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		9
	</div>
	<div class="cell" style="width:5%">
		{HOUR9}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT9}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		10
	</div>
	<div class="cell" style="width:5%">
		{HOUR10}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT10}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		11
	</div>
	<div class="cell" style="width:5%">
		{HOUR11}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT11}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		12
	</div>
	<div class="cell" style="width:5%">
		{HOUR12}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT12}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		13
	</div>
	<div class="cell" style="width:5%">
		{HOUR13}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT13}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		14
	</div>
	<div class="cell" style="width:5%">
		{HOUR14}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT14}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		15
	</div>
	<div class="cell" style="width:5%">
		{HOUR15}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT15}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		16
	</div>
	<div class="cell" style="width:5%">
		{HOUR16}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT16}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		17
	</div>
	<div class="cell" style="width:5%">
		{HOUR17}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT17}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		18
	</div>
	<div class="cell" style="width:5%">
		{HOUR18}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT18}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		19
	</div>
	<div class="cell" style="width:5%">
		{HOUR19}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT19}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		20
	</div>
	<div class="cell" style="width:5%">
		{HOUR20}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT20}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		21
	</div>
	<div class="cell" style="width:5%">
		{HOUR21}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT21}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		22
	</div>
	<div class="cell" style="width:5%">
		{HOUR22}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT22}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div>
</div>
<div class="row">
	<div class="cell" style="width:5%">
		23
	</div>
	<div class="cell" style="width:5%">
		{HOUR23}
	</div>
	<div class="cell" style="width:90%">
		<span class="cell" style="width:{PERCENT23}%;height:8px;margin:5px 0 5px 0;background-color:#963;"><br></span>
	</div></div>