		<div id="generalTab" class="cell tab_active" style="width:20%;" onclick="changeTab(this)">General</div>
		<div id="checklistTab" class="cell tab_inactive" style="width:20%;" onclick="changeTab(this)">Checklist</div>
		<div id="chargesTab" class="cell tab_inactive" style="width:19%;" onclick="changeTab(this)">Charges</div>
		<div id="administrationTab" class="cell tab_inactive" style="width:20%;" onclick="changeTab(this)">Administration</div>

